### PR TITLE
Update CUDA Docs to 12.1 support

### PR DESCRIPTION
**Pull request by siboehm**
Updated for the newest CUDA version.

Since the CUDA Docs aren't shipped with the cuda install anymore, I added a script to download them.

I'll keep testing this over the next few days and weeks. I may add more documentation pages later.

### CODE REVIEW

**Comment by siboehm** [comment]
I guess if you're not using this repo at all anymore I may just create a totally new one, or you can transfer ownership to me.

**Comment by siboehm** [comment]
Closes #2

**Comment by blahgeek** [comment]
> I guess if you're not using this repo at all anymore I may just create a totally new one, or you can transfer ownership to me.

Hi there,

Thanks for your interest in this repo. Indeed unfortunately I'm not maintaining this repo anymore. I don't think the transfer is necessary as you have already created a fork. I could update this repo's README to reflect the status of this repo, and add a link to your repo, if you want.

**Comment by siboehm** [comment]
Sounds good! See #4.

**Pull request closed without merging**
